<template>
  <div class="loadingio-spinner-spinner-x2hodd2fsa">
    <div class="ldio-o0y5mavovp">
      <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'LoadingSpinner'
}
</script>

<script setup></script>

<style scoped>
    @keyframes ldio-o0y5mavovp {
      0% { opacity: 1 }
      100% { opacity: 0 }
    }
    .ldio-o0y5mavovp div {
      left: 94px;
      top: 48px;
      position: absolute;
      animation: ldio-o0y5mavovp linear 1s infinite;
      background: #14a651;
      width: 12px;
      height: 24px;
      border-radius: 6px / 12px;
      transform-origin: 6px 52px;
    }.ldio-o0y5mavovp div:nth-child(1) {
      transform: rotate(0deg);
      animation-delay: -0.9649122807017544s;
      background: #14a651;
    }.ldio-o0y5mavovp div:nth-child(2) {
      transform: rotate(30deg);
      animation-delay: -0.8771929824561403s;
      background: #14a651;
    }.ldio-o0y5mavovp div:nth-child(3) {
      transform: rotate(60deg);
      animation-delay: -0.7894736842105263s;
      background: #14a651;
    }.ldio-o0y5mavovp div:nth-child(4) {
      transform: rotate(90deg);
      animation-delay: -0.7017543859649122s;
      background: #14a651;
    }.ldio-o0y5mavovp div:nth-child(5) {
      transform: rotate(120deg);
      animation-delay: -0.6140350877192983s;
      background: #14a651;
    }.ldio-o0y5mavovp div:nth-child(6) {
      transform: rotate(150deg);
      animation-delay: -0.5263157894736842s;
      background: #14a651;
    }.ldio-o0y5mavovp div:nth-child(7) {
      transform: rotate(180deg);
      animation-delay: -0.43859649122807015s;
      background: #14a651;
    }.ldio-o0y5mavovp div:nth-child(8) {
      transform: rotate(210deg);
      animation-delay: -0.3508771929824561s;
      background: #14a651;
    }.ldio-o0y5mavovp div:nth-child(9) {
      transform: rotate(240deg);
      animation-delay: -0.2631578947368421s;
      background: #14a651;
    }.ldio-o0y5mavovp div:nth-child(10) {
      transform: rotate(270deg);
      animation-delay: -0.17543859649122806s;
      background: #14a651;
    }.ldio-o0y5mavovp div:nth-child(11) {
      transform: rotate(300deg);
      animation-delay: -0.08771929824561403s;
      background: #14a651;
    }.ldio-o0y5mavovp div:nth-child(12) {
      transform: rotate(330deg);
      animation-delay: 0s;
      background: #14a651;
    }
    .loadingio-spinner-spinner-x2hodd2fsa {
      width: 200px;
      height: 200px;
      display: block;
      overflow: hidden;
      background: #ffffff;
      transform:scale(0.5);
      margin:auto;
    }
    .ldio-o0y5mavovp {
      width: 100%;
      height: 100%;
      position: relative;
      transform: translateZ(0) scale(1);
      backface-visibility: hidden;
      transform-origin: 0 0;
    }
    .ldio-o0y5mavovp div { box-sizing: content-box; }
    /* generated by https://loading.io/ */
</style>